# Generated by Django 5.0.7 on 2024-07-31 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_rename_if_available_car_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plocation', models.CharField(max_length=100)),
                ('dlocation', models.CharField(max_length=100)),
                ('pdate', models.DateField()),
                ('ddate', models.DateField()),
                ('time', models.TimeField()),
                ('is_status', models.CharField(default='pending', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
