# Generated by Django 5.0.7 on 2024-07-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('per_day_price', models.IntegerField()),
                ('per_hour_price', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('if_available', models.BooleanField(default=False)),
            ],
        ),
    ]
