# Generated by Django 5.0.7 on 2024-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=1, upload_to='cars\\image'),
            preserve_default=False,
        ),
    ]
