# Generated by Django 5.0.7 on 2024-07-31 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_car_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='if_available',
            new_name='is_published',
        ),
    ]
